name: MangoLimiter
version: 1.0
main: com.mangofuhrer.mangolimiter.MangoLimiter
api-version: 1.13
author: MangoFuhrer # MANGOFUHRER
description: Limits flight height for players unless they have a bypass permission.

commands:
  mangolimiter:
    description: Command for MangoLimiter
    usage: /<command>
    aliases: [ml]
    permission: mangolimiter.use
    permission-message: "You do not have permission to use MangoLimiter."

permissions:
  mangolimiter.use:
    description: Allows access to MangoLimiter commands
    default: op

  mangolimiter.bypass:
    description: Allows flying above the configured max height
    default: false
